### ISSUE TITLE
能提供个视频源 的演示吗?

### ISSUE THREAD

**Issue by freebacao** [sex-squirrel/video-collection-player#1]
如:
[
  {
    "id": "940c9043-f5f3-4907-96f6-c7a2a0d235da",
    "name": "某某资源站",
    "uri": "https://test.com.png",
    "httpApi": "http://test.com/api",
    "httpsApi": "http://test.com/sapi",
    "type": "某某资源"
  }
]

**Comment by SquirrelJimmy** [comment]
是这样的
