### ISSUE TITLE
请问视频源是以什么格式导入？

### ISSUE THREAD

**Issue by lidg888** [sex-squirrel/video-collection-player#2]
请问视频源是以什么格式导入？用h-player的视频文件*.json 导入不行。

**Comment by SquirrelJimmy** [comment]
参考h-player，偷个懒，这样可以通用

**Comment by freebacao** [comment]
@sex-squirrel 用h-player的 source.json 导入无效。点击上传视频源，浏览添加之后就返回了。

**Comment by SquirrelJimmy** [comment]
[{
    "id": 9,
    "name": "ok资源网",
    "uri": "http://www.jisudhw.com",
    "httpApi": "http://cj.okzy.tv/inc/ldg_seackm3u8.php",
    "httpsApi": "http://cj.okzy.tv/inc/ldg_seackm3u8s.php",
    "type": "影视"
  }]
按照此格式添加

**Comment by lidg888** [comment]
> [{{
> id } ：9，
> “名称”：“ ok资源网”，
> “ uri”：“ http://www.jisudhw.com”，
> “ httpApi”：“ http://cj.okzy.tv/inc /ldg_seackm3u8.php“，
> ” httpsApi“：” http://cj.okzy.tv/inc/ldg_seackm3u8s.php“，
> ” type“：”影视“
> }]
> 按照此格式添加

用这个格式试了还是不行，单击上传视频源，浏览添加之后就返回了。

**Comment by foqianyilishazi** [comment]
我这里也是的，我直接下载的 h-player的json格式的视频源，导入不到APP中 ，不知道怎么回事呢？

**Comment by afeizh** [comment]
h-player里是这样的:"id": "d240e1be-38aa-4356-88b8-d1febb48d95e",
都改成这样即可成功导入:"id": 12345,

**Comment by lidg888** [comment]
> h-player里是这样的：“ id”：“ d240e1be-38aa-4356-88b8-d1febb48d95e”，
> 都改成这样即可成功引入：“ id”：12345，

单击上传视频源，浏览添加之后就返回主页面了，视频源没有添加成功。软件各种权限都给了还是不行，你的可以吗？

**Comment by afeizh** [comment]
> > h-player里是这样的：“ id”：“ d240e1be-38aa-4356-88b8-d1febb48d95e”，
> > 都改成这样即可成功引入：“ id”：12345，
> 
> 单击上传视频源，浏览添加之后就返回主页面了，视频源没有添加成功。软件各种权限都给了还是不行，你的可以吗？

你把所有的id都改成数字,保存,再单击上传视频源,选择保存的文件,即可导入成功,我这么做没问题.保存编码utf8,

**Comment by lidg888** [comment]
> > > h-player里是这样的：“ id”：“ d240e1be-38aa-4356-88b8-d1febb48d95e”，
> > > 都改成这样即可成功发布：“ id”：12345，
> > 
> > 
> > 软件各种权限都给了还是不行，你的可以吗？
> 
> 您把所有的id都改成数字，保存，再重新上传视频源，选择保存的文件，即可导入成功，我以此没问题。保存编码utf8，

按照你的方法试了还是不行，可以把你的视频源发我试下吗？谢谢！邮箱：lidg888@gmail.com

**Comment by afeizh** [comment]
> > > > h-player里是这样的：“ id”：“ d240e1be-38aa-4356-88b8-d1febb48d95e”，
> > > > 都改成这样即可成功发布：“ id”：12345，
> > > 
> > > 
> > > 软件各种权限都给了还是不行，你的可以吗？
> > 
> > 
> > 您把所有的id都改成数字，保存，再重新上传视频源，选择保存的文件，即可导入成功，我以此没问题。保存编码utf8，
> 
> 按照你的方法试了还是不行，可以把你的视频源发我试下吗？谢谢！邮箱：[lidg888@gmail.com](mailto:lidg888@gmail.com)

“ id”：12345 可以
“ id”："12345" 不可以
似乎是这个原因

**Comment by lidg888** [comment]
> > > > > h-player里是这样的：“ id”：“ d240e1be-38aa-4356-88b8-d1febb48d95e”，
> > > > > 都改成这样即可成功发布：“ id”：12345，
> > > > 
> > > > 
> > > > 软件各种权限都给了还是不行，你的可以吗？
> > > 
> > > 
> > > 您把所有的id都改成数字，保存，再重新上传视频源，选择保存的文件，即可导入成功，我以此没问题。保存编码utf8，
> > 
> > 
> > 按照你的方法试了还是不行，可以把你的视频源发我试下吗？谢谢！邮箱：[lidg888@gmail.com](mailto:lidg888@gmail.com)
> 
> “ id”：12345 可以
> “ id”："12345" 不可以
> 似乎是这个原因

就是这个原因，非常感谢！

**Comment by SquirrelJimmy** [comment]
id使用数字，忘了为啥这样搞了，改下就行了
